title: Daniel M September
![Linkedin Picture](https://github.com/daniemseptember1/Portfolio/assets/70671940/d0455d38-7f24-46f9-8fdd-b8505b0acc93)
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
